Updated to work with angular 2.0.2
I'm unable to pull ng2-idle into my angular webpack application.  I get the following error:

Error: No provider for KeepaliveSvc!

Based on a previous issue - https://github.com/HackedByChinese/ng2-idle/issues/3 - I suspect that this is because I'm using angular 2.0.2 but ng2-idle was built against a specific angular patch release (2.0.0).  This change makes ng2-idle a little more friendly by allowing 2.0.x.